<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>SecureFlow.Cli</RootNamespace>
    <AssemblyName>secureflow</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SecureFlow.Core/SecureFlow.Core.csproj" />
    <ProjectReference Include="../SecureFlow.Ingest/SecureFlow.Ingest.csproj" />
  </ItemGroup>
</Project>
