using System.Text;
using SecureFlow.Api.Projects;
using SecureFlow.Core.Model;
using SecureFlow.Core.Simulation;

namespace SecureFlow.Api.Reports;

public static class ReportBuilder
{
    public static string Markdown(Project p)
    {
        var sb = new StringBuilder();
        var m = p.Model;
        var open = p.Findings.Where(f => f.Status == FindingStatus.Open).ToList();
        var fixedOnes = p.Findings.Where(f => f.Status == FindingStatus.Fixed).ToList();

        sb.AppendLine($"# {p.Name}: Resilience & Threat Model");
        sb.AppendLine();
        sb.AppendLine($"_Generated by SecureFlow on {DateTimeOffset.UtcNow:yyyy-MM-dd HH:mm} UTC from {p.Source}{(p.SourceRef is null ? "" : $" ({p.SourceRef})")}. AI reviewer: {p.AiProvider ?? "none"}._");
        sb.AppendLine();
        sb.AppendLine("## Scores");
        sb.AppendLine();
        sb.AppendLine("| | Score | Grade |");
        sb.AppendLine("|---|---|---|");
        sb.AppendLine($"| Resilience | **{p.Score.Resilience}** / 100 | {p.Score.ResilienceGrade} |");
        sb.AppendLine($"| Security | **{p.Score.Security}** / 100 | {p.Score.SecurityGrade} |");
        sb.AppendLine();
        sb.AppendLine($"Open findings: {open.Count} (" + string.Join(", ", p.Score.OpenBySeverity.Where(kv => kv.Value > 0).OrderByDescending(kv => kv.Key).Select(kv => $"{kv.Value} {kv.Key}")) + ").");
        if (p.History.Count > 1)
        {
            var first = p.History[0]; var last = p.History[^1];
            sb.AppendLine($"Since the first analysis: Resilience {first.Resilience} → {last.Resilience}, Security {first.Security} → {last.Security}, {fixedOnes.Count} finding(s) fixed.");
        }
        sb.AppendLine();

        if (p.Analysis is not null)
        {
            sb.AppendLine("## Executive summary");
            sb.AppendLine();
            sb.AppendLine(p.Analysis.ExecutiveSummary);
            sb.AppendLine();
            sb.AppendLine("**Most likely bad day.** " + p.Analysis.BusinessImpact);
            sb.AppendLine();
            if (p.Analysis.TopRisks.Count > 0)
            {
                sb.AppendLine("## Top risks");
                sb.AppendLine();
                var i = 1;
                foreach (var r in p.Analysis.TopRisks)
                {
                    sb.AppendLine($"{i++}. **{r.Title}** ({Names(m, r.ComponentIds)}). {r.Why}");
                }
                sb.AppendLine();
            }
            if (p.Analysis.QuickWins.Count > 0)
            {
                sb.AppendLine("## Quick wins");
                sb.AppendLine();
                foreach (var q in p.Analysis.QuickWins) sb.AppendLine($"- {q}");
                sb.AppendLine();
            }
        }

        sb.AppendLine("## Architecture");
        sb.AppendLine();
        if (!string.IsNullOrWhiteSpace(m.Description)) { sb.AppendLine(m.Description); sb.AppendLine(); }
        sb.AppendLine("| Component | Type | Tier | Replicas | Zones | Notes |");
        sb.AppendLine("|---|---|---|---|---|---|");
        foreach (var c in m.Components)
            sb.AppendLine($"| {c.Name} | {c.Type} | {c.Tier ?? ""} | {c.Props.Replicas?.ToString() ?? "?"} | {c.Props.Zones?.ToString() ?? "?"} | {c.Props.Technology ?? ""} |");
        sb.AppendLine();
        sb.AppendLine($"{m.Flows.Count} flows across {m.TrustBoundaries.Count} trust boundaries: " + string.Join("; ", m.TrustBoundaries.Select(b => $"**{b.Name}** ({Names(m, b.ComponentIds)})")) + ".");
        sb.AppendLine();

        // Blast radius of the three hottest components.
        var hottest = p.Score.ComponentHeat.OrderByDescending(kv => kv.Value).Take(3).Select(kv => kv.Key)
            .Where(id => m.FindComponent(id) is { } c && c.Type is not (ComponentType.User or ComponentType.External)).ToList();
        if (hottest.Count > 0)
        {
            sb.AppendLine("## Blast radius");
            sb.AppendLine();
            foreach (var id in hottest)
            {
                var r = BlastRadius.Simulate(m, id);
                sb.AppendLine($"- {r.Summary} ({r.BlastRatio:P0} of the system affected)");
            }
            sb.AppendLine();
        }

        sb.AppendLine("## Findings");
        sb.AppendLine();
        foreach (var group in open.GroupBy(f => f.Severity).OrderByDescending(g => g.Key))
        {
            sb.AppendLine($"### {group.Key} ({group.Count()})");
            sb.AppendLine();
            foreach (var f in group)
            {
                sb.AppendLine($"**{f.Title}** `{f.RuleId}` · {f.Category} / {f.Tag} · confidence {f.Confidence}  ");
                sb.AppendLine(f.Description + "  ");
                sb.AppendLine($"_Why:_ {f.Rationale}  ");
                sb.AppendLine($"_Fix:_ {f.Mitigation}  ");
                if (f.Evidence.Count > 0)
                    sb.AppendLine("_Evidence:_ " + string.Join("; ", f.Evidence.Take(3).Select(e => e.Path is null ? $"{e.Source}: {e.Snippet}" : $"`{e}` {Trunc(e.Snippet, 80)}")));
                sb.AppendLine();
            }
        }

        if (fixedOnes.Count > 0)
        {
            sb.AppendLine("## Fixed during this session");
            sb.AppendLine();
            foreach (var f in fixedOnes) sb.AppendLine($"- ~~{f.Title}~~: {f.Description}");
            sb.AppendLine();
        }

        if (m.Assumptions.Count > 0)
        {
            sb.AppendLine("## Assumptions made by the extractor");
            sb.AppendLine();
            foreach (var a in m.Assumptions) sb.AppendLine($"- {a}");
            sb.AppendLine();
        }

        sb.AppendLine("## Method");
        sb.AppendLine();
        sb.AppendLine("Findings marked with a rule id come from SecureFlow's deterministic rule catalog (resilience failure modes and STRIDE threats) evaluated over the extracted architecture model, so they are reproducible and explainable. Findings marked `AI` were added by the AI reviewer for context the rules cannot see, at medium confidence. Scores use a diminishing curve over severity-weighted open findings; an open Critical caps a score at 49 and an open High at 74.");
        return sb.ToString();
    }

    private static string Names(ArchitectureModel m, IEnumerable<string> ids) =>
        string.Join(", ", ids.Select(id => m.FindComponent(id)?.Name ?? id));

    private static string Trunc(string? s, int n) => s is null ? "" : s.Length <= n ? s : s[..n] + "…";
}
